### ISSUE TITLE
Investigate Sonar improvments

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-devops#114]
To try and split out FE and BE reporting by specifying we are a "monorepo". https://docs.sonarsource.com/sonarcloud/advanced-setup/monorepo-support/#convert-a-standard-project

Talk to Joseph Anderson if you have questions around why/what it should look like.

**Comment by dkrylovsb** [comment]
I created a test branch and made an isolated commit that affected back-end only. The commit produced a finding in Sonar as intented:
![image](https://github.com/CDCgov/prime-devops/assets/11096575/23d01c37-ff61-4d34-a7ea-f1cdd0c52bf6)

I then made a second commit isolated to the front-end code, which produced another finding. The findings did *not* overwrite -- they accumulated in Sonar: 
![image](https://github.com/CDCgov/prime-devops/assets/11096575/8019468e-f0ae-4a55-999a-2df24cd78ddf)

I think this is a non-issue because as @snesm mentioned "the SonarCloud functionality has been moved to a separate workflow so that it no longer directly impacts the frontend and backend builds".

**Comment by snesm** [comment]
As @dkrylovsb noted and tested, the current functionality is not failing.

IIRC the overwrite only occurs on merge to master, and will not occur with the current workflow configuration.  Unfortunately, changes to the workflow to show the overwrite/delete issue on merge to master will damage long term statistics used by SonarCloud.
